src/Atlas.UI/Models/ContatoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Atlas.UI.Models
{
    public class ContatoViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Informe o nome do contato")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Informe o apelido do contato")]
        public string Apelido { get; set; }
        public IEnumerable<TelefoneViewModel> Telefones { get; set; }
    }
}

src/Atlas.UI/Models/PagedResultViewModel.cs
using System;
using System.Collections.Generic;

namespace Atlas.UI.Models
{
    public class PagedResultViewModel<TResult>
    {
        public int Page { get; set; }
        public int Size { get; set; }
        public IEnumerable<TResult> Result { get; set; }
        public int Count { get; set; }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)Count / Size); }
        }
    }
}

src/Atlas.UI/Controllers/ContatosController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Atlas.UI.Domain;
using Atlas.UI.Infra;
using Atlas.UI.Models;
using AutoMapper;
using Raven.Client;
using Raven.Client.Linq;

namespace Atlas.UI.Controllers
{
    public class ContatosController : RavenController
    {
        public ContatosController(IDocumentSession documentSession)
            : base(documentSession)
        {
        }

        //
        // GET: /
        [HttpGet]
        public ActionResult Index(string term = null, int page = 1, int size = 20)
        {
            RavenQueryStatistics stats;
            IRavenQueryable<Contato_Search.ContatoSearch> query = null;

            if (!string.IsNullOrEmpty(term))
                query = DocumentSession.Query<Contato_Search.ContatoSearch, Contato_Search>()
                .Statistics(out stats)
                    .Search(c => c.Query,string.Format("*{0}*",term), escapeQueryOptions: EscapeQueryOptions.AllowAllWildcards);
            else
                query = DocumentSession.Query<Contato_Search.ContatoSearch, Contato_Search>()
                    .Statistics(out stats);
             
                var contatos = query
                .Skip((page - 1)*size)
                .Take(size)
                .OrderBy(c=>c.Nome)
                .As<Contato>()
                .ToList();

            ViewBag.Term = term ?? string.Empty;

            var result = new PagedResultViewModel<ContatoViewModel>
                {
                    Page = page,
                    Size = size,
                    Result = Mapper.Map<IEnumerable<Contato>, IEnumerable<ContatoViewModel>>(contatos),
                    Count = stats.TotalResults
                };

            
            return RespondTo(normal: () => View("Index", result),
                             ajax: () => PartialView("_Contatos", result));

        }

        //
        // POST: /Contatos/
        [HttpPost]
        public ActionResult Create(ContatoViewModel contatoViewModel)
        {
            if (!ModelState.IsValid) return View("New", contatoViewModel);

            var contato = DocumentSession
               .Query<Contato_Search.ContatoSearch, Contato_Search>()
               .As<Contato>()
               .FirstOrDefault(c => c.Nome == contatoViewModel.Nome);

            if(null == contato)
            {
                contato = Mapper.Map<ContatoViewModel, Contato>(contatoViewModel);
                DocumentSession.Store(contato);
                TempData["success"] = "Contato incluido com sucesso";
            }
            else
            {
                TempData["error"] = string.Format("Já existe um contato com o nome {0}", contato.Nome);
            }

            return RedirectToAction("Edit", new {contato.Id});
         
        }

        //
        // GET: /Contatos/New
        [HttpGet]
        public ActionResult New()
        {
            return View("New");
        }

        //
        // GET: /Contatos/[id]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var contato = DocumentSession.Load<Contato>(id);

            return View("Edit", Mapper.Map<Contato, ContatoViewModel>(contato));
        }

        //
        // POST: /Contatos/[id]
        [HttpPost]
        public ActionResult Update(int id, ContatoViewModel viewModel)
        {
            var contato = DocumentSession
                .Query<Contato_Search.ContatoSearch, Contato_Search>()
                .As<Contato>()
                .FirstOrDefault(c => c.Nome == viewModel.Nome &&
                                     c.Id != viewModel.Id);

            if (null == contato)
            {
                contato = DocumentSession.Load<Contato>(id);

                contato.Apelido = viewModel.Apelido;
                contato.Nome = viewModel.Nome;

                TempData["success"] = "Contato atualizado com sucesso";

                return RedirectToAction("Index");
            }

            TempData["error"] = string.Format("Já existe um contato com o nome {0}", contato.Nome);

            return RedirectToAction("Edit", new {id = contato.Id});
        }

        //
        // DELETE: /Contatos/[id]
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var contato = DocumentSession.Load<Contato>(id);
            DocumentSession.Delete(contato);

            TempData["success"] = "Contato deletado com sucesso";

            return null;
        }

        //
        // POST: /Contatos/[id]/AddPhone
        [HttpPost]
        public ActionResult AddPhone(int id, TelefoneViewModel viewModel)
        {
            if (!ModelState.IsValid) return RedirectToAction("Edit",new {id});

            var contato = DocumentSession.Load<Contato>(id);
            var telefone = Mapper.Map<Telefone>(viewModel);

            contato.IncluiTelefone(telefone);

            TempData["success"] = string.Format("Telefone {0} adicionado.", telefone);

            return View("Edit", Mapper.Map<Contato, ContatoViewModel>(contato));
        }

        //
        // POST: /Contatos/[id]/DeletePhone
        [HttpPost]
        public ActionResult DeletePhone(int id, TelefoneViewModel telefoneViewModel)
        {
            var telefone = Mapper.Map<TelefoneViewModel, Telefone>(telefoneViewModel);
            
            var contato = DocumentSession.Load<Contato>(id);

            contato.RemoveTelefone(telefone);

            TempData["success"] = string.Format("Telefone {0} removido.", telefone);

            return null;
        }

        //
        // GET: /Contatos/[id]/AddPhone
        [HttpGet]
        public ActionResult AddPhone(int id)
        {
            ViewBag.ContatoId = id;
            return PartialView("_AddPhone");
        }
    }
}

src/Atlas.UI/Views/Contatos/Edit.cshtml
@model Atlas.UI.Models.ContatoViewModel
@{
    ViewBag.Title = "Editando";
}

@using (Html.BeginForm("Update", "Contatos", FormMethod.Post))
{
    @Html.Partial("_Form", Model)
}

<a href="@Url.Action("AddPhone","Contatos", new {id = Model.Id})" class="openModal edit" data-width="500px" data-method="GET">Incluir Telefone</a>
@Html.Partial("_Telefones",Model)

@Html.ActionLink("Voltar","Index","Contatos",null,new{@class="edit"})

@section header
{
    <link href="@Url.Content("~/Public/css/form.css")" rel="stylesheet" media="all" type="text/css"/>
}

src/Atlas.UI/Views/Contatos/Index.cshtml
@model Atlas.UI.Models.PagedResultViewModel<Atlas.UI.Models.ContatoViewModel>

@{
    ViewBag.Title = "Contatos";
}

@Html.Partial("_Search",(string)ViewBag.Term)

<br />

@Html.ActionLink("Adicionar","New","Contatos",null,new{@class="edit"})

<ul id="contatos" 
    data-url="@Url.Action("Index","Contatos")" 
    data-total-pages="@Model.TotalPages" 
    data-params='{"term":"@ViewBag.Term"}'>
    @Html.Partial("_Contatos",Model)
</ul>

src/Atlas.UI/Views/Contatos/New.cshtml
@model Atlas.UI.Models.ContatoViewModel

@{
    ViewBag.Title = "Novo";
}

@using(Html.BeginForm("Create","Contatos",FormMethod.Post))
{
   @Html.Partial("_Form",Model)
}

@Html.ActionLink("Voltar","Index","Contatos",null,new{@class="edit"})

@section header
{
    <link href="@Url.Content("~/Public/css/form.css")" rel="stylesheet" media="all" type="text/css"/>
}

src/Atlas.UI/Views/Contatos/_AddPhone.cshtml
@model Atlas.UI.Models.TelefoneViewModel
<form action="@Url.Action("AddPhone","Contatos",new {id = ViewBag.ContatoId})" method="POST">
    <div class="field">
        @Html.LabelFor(c=>c.Numero)
        @Html.TextBoxFor(c=>c.Numero)
        @Html.ValidationMessageFor(c=>c.Numero)
    </div>
    <div class="field">
        @Html.LabelFor(c=>c.Operadora)
        <select id="Operadora" name="Operadora">
            <option value="Claro">Claro</option>
            <option value="Tim">Tim</option>
            <option value="Vivo">Vivo</option>
            <option value="Telefonica">Telefonica</option>
            <option value="Embratel">Embratel</option>
            <option value="Oi">Oi</option>
            <option value="Net">Net</option>
        </select>
        @Html.ValidationMessageFor(c=>c.Operadora)
    </div>
    <input type="submit" class="edit" value="Salvar"/>
</form>
<script src="@Url.Content("~/Public/js/libs/jquery.validate.unobtrusive.min.js")"></script>


src/Atlas.UI/Views/Contatos/_Contatos.cshtml
@model Atlas.UI.Models.PagedResultViewModel<Atlas.UI.Models.ContatoViewModel>

@foreach(var contato in Model.Result)
    {
        <li class="contato">
            @Html.DisplayFor(c => contato)
        </li>
    }

src/Atlas.UI/Views/Contatos/_Form.cshtml
@model Atlas.UI.Models.ContatoViewModel

<div class="field">
    @Html.LabelFor(c=>c.Nome)
    @Html.TextBoxFor(c=>c.Nome)
    @Html.ValidationMessageFor(c=>c.Nome)
</div>
<div class="field">
    @Html.LabelFor(c=>c.Apelido)
    @Html.TextBoxFor(c=>c.Apelido)
    @Html.ValidationMessageFor(c=>c.Apelido)
</div>

<input type="submit" value="Salvar" class="edit"/>

src/Atlas.UI/Views/Contatos/_Search.cshtml
@model string
@using(Html.BeginForm("Index","Contatos",FormMethod.Get))
{
    <input type="text" id="term" name="term" placeholder="Digite o termo da busca..." value="@Model"/> <input class="edit" id="pesquisar" type="submit" value="Pesquisar"/>
}

src/Atlas.UI/Views/Contatos/_Telefones.cshtml
@model Atlas.UI.Models.ContatoViewModel

@if (null != Model.Telefones && Model.Telefones.Any())
{
    <table>
        <tr>
            <th>Numero</th>
            <th>Operadora</th>
            <th></th>
        </tr>
        @foreach (var telefone in Model.Telefones)
        {
            <tr>
                <td>@telefone.Numero</td>
                <td>@telefone.Operadora</td>
                <td><a href="@Url.Action("DeletePhone", "Contatos", new {id = Model.Id})"
                       class="excluir edit"
                       data-method="post"
                       data-redirect="@Url.Action("Edit", "Contatos", new {id = Model.Id})" 
                       data-params='{"Operadora":"@telefone.Operadora","Numero":"@telefone.Numero"}'>Excluir</a></td>
            </tr>
        }
    </table>
}

src/Atlas.UI/Views/Shared/DisplayTemplates/ContatoViewModel.cshtml
@using Atlas.UI.Infra
@model Atlas.UI.Models.ContatoViewModel
<div class="title">
    <a href="@Url.Action("Edit","Contatos",new{id = Model.Id})">@Html.Highlight(Model.Nome,(string)ViewBag.Term) (@Html.Highlight(Model.Apelido,(string)ViewBag.Term))</a>
    @Html.ActionLink("Excluir","Delete","Contatos",new{id = Model.Id},new{@class="excluir"})
</div>

src/Atlas.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Atlas - @ViewBag.Title</title>
    <link href="@Url.Content("~/Public/css/jquery.ui/jquery-ui-1.8.24.custom.css")" rel="stylesheet" media="all" type="text/css"/>
    <link href="@Url.Content("~/Public/css/site.css")" rel="stylesheet" media="all" type="text/css"/>
    @RenderSection("header",false)
</head>
    <body>
        <div id="main" data-yield="main">
            @if (null != TempData["success"])
            {
                <div id="error-message" class="success">
                    @TempData["success"]
                    @TempData["error"]
                </div>
            }
            @if (null != TempData["error"])
            {
                <div id="error-message">
                    @TempData["error"]
                </div>
            }
            <div id="wrap">
                @RenderBody()
            </div>
        </div>
        <div id="modal"></div>
        <script src="@Url.Content("~/Public/js/libs/jquery-1.8.2.min.js")"></script>
        <script src="@Url.Content("~/Public/js/libs/jquery-ui-1.8.24.custom.min.js")"></script>
        <script src="@Url.Content("~/Public/js/libs/jquery.validate.min.js")"></script>
        <script src="@Url.Content("~/Public/js/libs/jquery.validate.unobtrusive.min.js")"></script>
        <script src="@Url.Content("~/Public/js/libs/jquery.pageless.min.js")"></script>
        <script src="@Url.Content("~/Public/js/app.js")"></script>
    </body>
</html>